### ISSUE TITLE
Controller Spawner couldn't find the expected controller_manager ROS interface

### ISSUE THREAD

**Issue by bj-neilson** [SigmaEmbeddedEngineering/Sigmapilot#1]
Hi,
The packages you've done look good.  Your list of future features looks even better.  I've had a go at running the packages but am running into a few errors.  I think this problem finding the expected controller_manager ROS interface might be causing several of the issues.  Did you have any of these problems as below so far?

Thanks
Ben

:~/autobotware_ws$ roslaunch autobotware_simulator robot_navigation.launch sensor:=velodyne world_name:='$(find autobotware_simulator)/worlds/turtlebot3_world.world' map_file:='$(find autobotware_simulator)/maps/map.yaml'
... logging to /home/ben/.ros/log/0e256c5c-b2d7-11eb-929a-30d16b9fbdab/roslaunch-ben-Aspire-2794.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://ben-Aspire:46213/

SUMMARY
========

PARAMETERS
 * /LiDAR_topicname: ['/LiDAR1/pcl']
 * /amcl/base_frame_id: robot_footprint
 * /amcl/gui_publish_rate: 50.0
 * /amcl/initial_pose_a: 0.0
 * /amcl/initial_pose_x: 0.0
 * /amcl/initial_pose_y: 0.0
 * /amcl/kld_err: 0.02
 * /amcl/laser_lambda_short: 0.1
 * /amcl/laser_likelihood_max_dist: 2.0
 * /amcl/laser_max_beams: 180
 * /amcl/laser_max_range: 10
 * /amcl/laser_model_type: likelihood_field
 * /amcl/laser_sigma_hit: 0.2
 * /amcl/laser_z_hit: 0.5
 * /amcl/laser_z_max: 0.05
 * /amcl/laser_z_rand: 0.5
 * /amcl/laser_z_short: 0.05
 * /amcl/max_particles: 200
 * /amcl/min_particles: 100
 * /amcl/odom_alpha1: 0.1
 * /amcl/odom_alpha2: 0.1
 * /amcl/odom_alpha3: 0.1
 * /amcl/odom_alpha4: 0.1
 * /amcl/odom_frame_id: odom
 * /amcl/odom_model_type: diff
 * /amcl/recovery_alpha_fast: 0.0
 * /amcl/recovery_alpha_slow: 0.0
 * /amcl/resample_interval: 1
 * /amcl/transform_tolerance: 0.5
 * /amcl/update_min_a: 0.2
 * /amcl/update_min_d: 0.2
 * /gazebo/enable_ros_network: True
 * /joint_state_publisher/use_gui: False
 * /move_base/DWAPlannerROS/acc_lim_theta: 3.2
 * /move_base/DWAPlannerROS/acc_lim_x: 2.5
 * /move_base/DWAPlannerROS/acc_lim_y: 0.0
 * /move_base/DWAPlannerROS/controller_frequency: 10.0
 * /move_base/DWAPlannerROS/forward_point_distance: 0.325
 * /move_base/DWAPlannerROS/goal_distance_bias: 20.0
 * /move_base/DWAPlannerROS/latch_xy_goal_tolerance: False
 * /move_base/DWAPlannerROS/max_scaling_factor: 0.2
 * /move_base/DWAPlannerROS/max_vel_theta: 2.75
 * /move_base/DWAPlannerROS/max_vel_trans: 0.22
 * /move_base/DWAPlannerROS/max_vel_x: 0.22
 * /move_base/DWAPlannerROS/max_vel_y: 0.0
 * /move_base/DWAPlannerROS/min_vel_theta: 1.37
 * /move_base/DWAPlannerROS/min_vel_trans: 0.11
 * /move_base/DWAPlannerROS/min_vel_x: -0.22
 * /move_base/DWAPlannerROS/min_vel_y: 0.0
 * /move_base/DWAPlannerROS/occdist_scale: 0.02
 * /move_base/DWAPlannerROS/oscillation_reset_dist: 0.05
 * /move_base/DWAPlannerROS/path_distance_bias: 32.0
 * /move_base/DWAPlannerROS/publish_cost_grid_pc: True
 * /move_base/DWAPlannerROS/publish_traj_pc: True
 * /move_base/DWAPlannerROS/scaling_speed: 0.25
 * /move_base/DWAPlannerROS/sim_time: 1.5
 * /move_base/DWAPlannerROS/stop_time_buffer: 0.2
 * /move_base/DWAPlannerROS/vth_samples: 40
 * /move_base/DWAPlannerROS/vx_samples: 20
 * /move_base/DWAPlannerROS/vy_samples: 0
 * /move_base/DWAPlannerROS/xy_goal_tolerance: 0.1
 * /move_base/DWAPlannerROS/yaw_goal_tolerance: 0.5
 * /move_base/base_local_planner: dwa_local_planner...
 * /move_base/conservative_reset_dist: 3.0
 * /move_base/controller_frequency: 10.0
 * /move_base/controller_patience: 15.0
 * /move_base/global_costmap/cost_scaling_factor: 3.0
 * /move_base/global_costmap/footprint: [[-0.276, -0.23],...
 * /move_base/global_costmap/global_frame: map
 * /move_base/global_costmap/inflation_radius: 1.0
 * /move_base/global_costmap/map_type: costmap
 * /move_base/global_costmap/observation_sources: scan
 * /move_base/global_costmap/obstacle_range: 3.0
 * /move_base/global_costmap/publish_frequency: 10.0
 * /move_base/global_costmap/raytrace_range: 3.5
 * /move_base/global_costmap/robot_base_frame: robot_footprint
 * /move_base/global_costmap/scan/clearing: True
 * /move_base/global_costmap/scan/data_type: LaserScan
 * /move_base/global_costmap/scan/marking: True
 * /move_base/global_costmap/scan/sensor_frame: coloredLidar
 * /move_base/global_costmap/scan/topic: clusteredPointCLo...
 * /move_base/global_costmap/static_map: True
 * /move_base/global_costmap/transform_tolerance: 0.5
 * /move_base/global_costmap/update_frequency: 10.0
 * /move_base/local_costmap/cost_scaling_factor: 3.0
 * /move_base/local_costmap/footprint: [[-0.276, -0.23],...
 * /move_base/local_costmap/global_frame: odom
 * /move_base/local_costmap/height: 3
 * /move_base/local_costmap/inflation_radius: 1.0
 * /move_base/local_costmap/map_type: costmap
 * /move_base/local_costmap/observation_sources: scan
 * /move_base/local_costmap/obstacle_range: 3.0
 * /move_base/local_costmap/publish_frequency: 10.0
 * /move_base/local_costmap/raytrace_range: 3.5
 * /move_base/local_costmap/resolution: 0.05
 * /move_base/local_costmap/robot_base_frame: robot_footprint
 * /move_base/local_costmap/rolling_window: True
 * /move_base/local_costmap/scan/clearing: True
 * /move_base/local_costmap/scan/data_type: LaserScan
 * /move_base/local_costmap/scan/marking: True
 * /move_base/local_costmap/scan/sensor_frame: coloredLidar
 * /move_base/local_costmap/scan/topic: clusteredPointCLo...
 * /move_base/local_costmap/static_map: False
 * /move_base/local_costmap/transform_tolerance: 0.5
 * /move_base/local_costmap/update_frequency: 10.0
 * /move_base/local_costmap/width: 3
 * /move_base/oscillation_distance: 0.2
 * /move_base/oscillation_timeout: 10.0
 * /move_base/planner_frequency: 5.0
 * /move_base/planner_patience: 5.0
 * /move_base/shutdown_costmaps: False
 * /point_cloud_assembler/odom_frame: odom
 * /point_cloud_assembler/pub_topicname: /assemblerMap
 * /point_cloud_assembler/tf_duration: 0.1
 * /point_cloud_assembler/voxel_size: 0.2
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /rqt_robot_steering/default_topic: /cmd_vel
 * /sgm_lidar_clustering/LiDAR_topicname: /LiDAR1/pcl
 * /sgm_lidar_clustering/distance_threshold: 0.5
 * /sgm_lidar_clustering/distance_threshold_type: 1.0
 * /sgm_lidar_clustering/ground_segmentation_threshold: 0.2
 * /sgm_lidar_clustering/lidar_max_range: 30.0
 * /sgm_lidar_clustering/max_horizontal_angle: 3.14159
 * /sgm_lidar_clustering/min_horizontal_angle: -3.14159
 * /sgm_lidar_clustering/obj_level_filter_flag: True
 * /sgm_lidar_clustering/obj_level_vol_threshold: 0.1
 * /sgm_lidar_clustering/obj_level_x_max: 2.0
 * /sgm_lidar_clustering/obj_level_x_min: 0.01
 * /sgm_lidar_clustering/obj_level_y_max: 2.0
 * /sgm_lidar_clustering/obj_level_y_min: 0.01
 * /sgm_lidar_clustering/obj_level_z_max: 2.0
 * /sgm_lidar_clustering/obj_level_z_min: 0.1
 * /sgm_lidar_clustering/pub_ma_topicname: clusteredObjectList
 * /sgm_lidar_clustering/pub_pc_topicname: clusteredPointCLoud
 * /skid_steer_bot/hardware_interface/joints: ['left_back_wheel...
 * /skid_steer_bot/joint_state_controller/publish_rate: 50
 * /skid_steer_bot/joint_state_controller/type: joint_state_contr...
 * /skid_steer_bot/mobile_base_controller/angular/z/has_acceleration_limits: True
 * /skid_steer_bot/mobile_base_controller/angular/z/has_velocity_limits: True
 * /skid_steer_bot/mobile_base_controller/angular/z/max_acceleration: 6.0
 * /skid_steer_bot/mobile_base_controller/angular/z/max_velocity: 2.0
 * /skid_steer_bot/mobile_base_controller/base_frame_id: robot_footprint
 * /skid_steer_bot/mobile_base_controller/left_back_wheel: left_back_wheel_h...
 * /skid_steer_bot/mobile_base_controller/left_front_wheel: left_front_wheel_...
 * /skid_steer_bot/mobile_base_controller/linear/x/has_acceleration_limits: True
 * /skid_steer_bot/mobile_base_controller/linear/x/has_velocity_limits: True
 * /skid_steer_bot/mobile_base_controller/linear/x/max_acceleration: 0.6
 * /skid_steer_bot/mobile_base_controller/linear/x/max_velocity: 0.2
 * /skid_steer_bot/mobile_base_controller/pose_covariance_diagonal: [0.001, 0.001, 0....
 * /skid_steer_bot/mobile_base_controller/publish_rate: 50
 * /skid_steer_bot/mobile_base_controller/right_back_wheel: right_back_wheel_...
 * /skid_steer_bot/mobile_base_controller/right_front_wheel: right_front_wheel...
 * /skid_steer_bot/mobile_base_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
 * /skid_steer_bot/mobile_base_controller/type: skid_steer_drive_...
 * /skid_steer_bot/mobile_base_controller/wheel_radius: 0.16
 * /skid_steer_bot/mobile_base_controller/wheel_separation: 0.46
 * /use_sim_time: True

NODES
  /
    amcl (amcl/amcl)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    map_server (map_server/map_server)
    move_base (move_base/move_base)
    point_cloud_assembler (point_cloud_assembler/point_cloud_assembler)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)
    rviz (rviz/rviz)
    rviz_assembler (rviz/rviz)
    rviz_cluster (rviz/rviz)
    sgm_lidar_clustering (sgm_lidar_clustering/sgm_lidar_clustering)
    urdf_spawner (gazebo_ros/spawn_model)
  /skid_steer_bot/
    controller_spawner (controller_manager/spawner)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)

auto-starting new master
process[master]: started with pid [2817]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0e256c5c-b2d7-11eb-929a-30d16b9fbdab
process[rosout-1]: started with pid [2829]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [2836]
process[robot_state_publisher-3]: started with pid [2837]
process[gazebo-4]: started with pid [2838]
process[gazebo_gui-5]: started with pid [2842]
process[urdf_spawner-6]: started with pid [2848]
process[sgm_lidar_clustering-7]: started with pid [2849]
process[rviz_cluster-8]: started with pid [2855]
process[skid_steer_bot/controller_spawner-9]: started with pid [2857]
process[skid_steer_bot/robot_state_publisher-10]: started with pid [2858]
process[rqt_robot_steering-11]: started with pid [2860]
process[point_cloud_assembler-12]: started with pid [2864]
process[rviz_assembler-13]: started with pid [2870]
process[map_server-14]: started with pid [2872]
process[amcl-15]: started with pid [2873]
process[move_base-16]: started with pid [2874]
process[rviz-17]: started with pid [2879]
[ WARN] [1620792231.125411350]: Request for map failed; trying again...
initialize
obj_level_filter_flag: 1
gnd_seg_threshold: 0.2
distance_threshold: 0.5
point cloud sub topic: /LiDAR1/pcl
point cloud pub topic: clusteredPointCLoud
object pub topic: clusteredObjectList
initialize
[ WARN] [1620792231.209772414]: Transformer::setExtrapolationLimit is deprecated and does not do anything
topic_names: /LiDAR1/pcl
[INFO] [1620792231.443291, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1620792231.679502515]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1620792231.682827108]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1620792231.775294137]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1620792231.777715675]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1620792232.192907, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1620792232.214761, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[WARN] [1620792261.605422, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[skid_steer_bot/controller_spawner-9] process has finished cleanly
log file: /home/ben/.ros/log/0e256c5c-b2d7-11eb-929a-30d16b9fbdab/skid_steer_bot-controller_spawner-9*.log
Error Code: 11 Msg: Unable to find uri[model://turtlebot3_world]
[ INFO] [1620792408.824979260]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1620792408.888664318, 0.035000000]: Physics dynamic reconfigure ready.
[INFO] [1620792408.943346, 0.087000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1620792409.494303193, 0.200000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1620792409.501556006, 0.200000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
Service call failed: transport error completing service call: receive_once[/gazebo/spawn_urdf_model]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
[ERROR] [1620792419.940837, 0.200000]: Spawn service failed. Exiting.
[ INFO] [1620792419.941907352, 0.200000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1620792419.942079448, 0.200000000]: x:0.000000, y:0.000000,z:0.000000,roll:0.000000,pitch:0.000000,yaw:0.000000
[ INFO] [1620792419.942223790, 0.200000000]: Starting Laser Plugin (ns = /)
[ INFO] [1620792419.949228264, 0.200000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1620792420.051874323, 0.200000000]: Starting GazeboRosSkidSteerDrive Plugin (ns = //)
[ INFO] [1620792420.089983321, 0.200000000]: Loading gazebo_ros_control plugin
[ INFO] [1620792420.090285054, 0.200000000]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1620792420.091749457, 0.200000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[urdf_spawner-6] process has died [pid 2848, exit code 1, cmd /home/ben/catkin_ws/src/AutoOrchards_mower/gazebo_ros_pkgs/gazebo_ros/scripts/spawn_model -x -2 -y 0.5 -Y 0 -urdf -param robot_description -model skid_steer_bot __name:=urdf_spawner __log:=/home/ben/.ros/log/0e256c5c-b2d7-11eb-929a-30d16b9fbdab/urdf_spawner-6.log].
log file: /home/ben/.ros/log/0e256c5c-b2d7-11eb-929a-30d16b9fbdab/urdf_spawner-6*.log
[ INFO] [1620792420.230847021, 0.200000000]: Loaded gazebo_ros_control.
PointCloud after filtering: 1712  1  before filtering:32768  accumilative filtering:1712
OpenCV Error: Assertion failed (src.type() == CV_8UC1) in findNonZero, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/stat.cpp, line 4043
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/stat.cpp:4043: error: (-215) src.type() == CV_8UC1 in function findNonZero

PointCloud after filtering: 1707  1  before filtering:32768  accumilative filtering:3181
[sgm_lidar_clustering-7] process has died [pid 2849, exit code -6, cmd /home/ben/autobotware_ws/devel/lib/sgm_lidar_clustering/sgm_lidar_clustering __name:=sgm_lidar_clustering __log:=/home/ben/.ros/log/0e256c5c-b2d7-11eb-929a-30d16b9fbdab/sgm_lidar_clustering-7.log].
log file: /home/ben/.ros/log/0e256c5c-b2d7-11eb-929a-30d16b9fbdab/sgm_lidar_clustering-7*.log
PointCloud after filtering: 1698  1  before filtering:32768  accumilative filtering:3727
PointCloud after filtering: 1720  1  before filtering:32768  accumilative filtering:4017

**Comment by khaledelmadawi** [comment]
I think your problem in the opencv version, as it is 3.2.0, I would recommend you to update ur opencv version to 4.5+

**Comment by khaledelmadawi** [comment]
issue will be closed
